REGISTRATION_EMAIL = "REGISTRATION_EMAIL"
NEW_COVID_TO_RESTAURANT_BOOKING = "NEW_COVID_TO_RESTAURANT_BOOKING"
NEW_POSITIVE_WAS_IN_RESTAURANT = "NEW_POSITIVE_WAS_IN_RESTAURANT"
EMAIL_TO_FRIEND = "EMAIL_TO_FRIEND"
NEW_POSITIVE_CONTACT = "NEW_POSITIVE_CONTACT"
CONFIRMATION_BOOKING = "CONFIRMATION_BOOKING"
CALCULATE_RATING_RESTAURANTS = "CALCULATE_RATING_RESTAURANTS"
CALCULATE_RATING_RESTAURANT = "CALCULATE_RATING_RESTAURANT"

# ------------ MICROSERVICE URL CONSTANT ----------------------------
USER_MICROSERVICE_URL = "http://ngnix/user"
